---
subdomains:
  - name: "CCN"
    subdomain: "prexbff.citizens.com.mm"
  - name: "Latcom"
    subdomain: "bff.mitopup.com"
  - name: "NassWallet"
    subdomain: "gw-api.nasswallet.com"
  - name: "AnyPay"
    subdomain: "bff.anypay.ao"
  - name: "APS"
    subdomain: "bff.apswallet.gm"
  - name: "CRDB"
    subdomain: "bff-prd.crdbbank.co.tz"
  - name: "QCellGM"
    subdomain: "bffelite.qmoney.gm"
  - name: "CityBank"
    subdomain: "dobbff.thecitybank.com"
  - name: "QCellSL"
    subdomain: "bffelite.qmoney.sl"
  - name: "LyFiMoney"
    subdomain: "bff.lyfimoney.com"
  - name: "WalletMicroFin"
    subdomain: "bff.walletbir.com"
