---
- name: Audit Report Role - Load Average
  hosts: sshuser
#  vars_files:
#    - group_vars/audit-report-variables.yml
  become: yes
  tasks:
    - name: Get load average
      shell: "cat /proc/loadavg | awk '{print $1}'"
      register: loadresult

    - name: Get timestamp
      shell: date +"%Y-%m-%d %H:%M:%S"
      register: time

    - name: Save load average to a file
      lineinfile:
        line: "{{ loadresult.stdout }},{{ time.stdout }}"
        path: "/root/Ansible/QMoneyGM/Load/{{ ansible_default_ipv4.address }}/Loadeverage.yml"
        create: yes
      delegate_to: localhost
