---
- name: Audit Report Role - Uptime and Time Sync
  hosts: uptime_timesync
  vars_files:
    - /root/Ansible/QMoneyGM/audit-report-variables.yml
  #remote_user: vicky.kariya
  become: yes
  roles :
    - uptime_timesync
