---
- name: Audit Report Role - Version Check
  hosts: versioncheckvault
  vars_files:
    - group_vars/audit-report-variables.yml
  #remote_user: vicky.kariya
  become: yes
  serial: 1
  roles :
    - versioncheckvault
