---
- name: Run MySQL query - Count Transactional Master Rows - CR
  shell: |
    mysql -h 172.16.10.49 -u SupportLead -P 6055 -pQw12s#fdga MobifinEliteTransactionEngine_QCell -e "SELECT COUNT(*) FROM TBLTransactionHistory WHERE TransactionType='CR'" | sed 's/\t/,/g' | awk 'NR==2 {print $1}'
  register: tmrcr_18_20_result
  when: MR == "18" or MR == "20"

- name: Run MySQL query - Count Transactional Master Rows - DR
  shell: |
    mysql -h 172.16.10.49 -u SupportLead -P 6055 -pQw12s#fdga MobifinEliteTransactionEngine_QCell -e "SELECT COUNT(*) FROM TBLTransactionHistory WHERE TransactionType='DR'" | sed 's/\t/,/g' | awk 'NR==2 {print $1}'
  register: tmrdr_18_20_result
  when: MR == "18" or MR == "20"

#- name: Print output in file
#  lineinfile:
#    path: {{ DIRECTORY }}/{{ PROJECT }}_audit_report_db_{{ lookup('pipe', 'date +%d%m%Y') }}.txt
#    line: "Count of Transactional master rows is CR = {{ tmrcr_18_20_result.stdout }} + DR = {{ tmrdr_18_20_result.stdout }}"
#    create: yes
#  delegate_to: localhost
#  when: MR == "18" or MR == "20"

- name: Print output in file
  lineinfile:
    path: "{{ DIRECTORY }}/{{ PROJECT }}_Audit_Report_Metrics_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
    line: "Count of Transactional master rows,CR,{{ tmrcr_18_20_result.stdout }},DR,{{ tmrdr_18_20_result.stdout }}"
    create: yes
    insertafter: EOF
  delegate_to: localhost
  when: MR == "18" or MR == "20"

- name: Run MySQL query - Count Transactional Master Rows
  shell: |
    mysql -h 172.16.10.49 -u SupportLead -P 6055 -pQw12s#fdga MobifinEliteTransactionEngine_QCell -e "SELECT COUNT(*) FROM TBLTransactionHSTMain" | sed 's/\t/,/g' | awk 'NR==2 {print $1}'
  register: tmr_21_result
  when: MR == "21"

#- name: Print output in file
#  lineinfile:
#    path: {{ DIRECTORY }}/{{ PROJECT }}_audit_report_db_{{ lookup('pipe', 'date +%d%m%Y') }}.txt
#    line: "Count of Transactional master rows is {{ tmr_21_result.stdout }}"
#    create: yes
#  delegate_to: localhost
#  when: MR == "21"

- name: Print output in file
  lineinfile:
    path: "{{ DIRECTORY }}/{{ PROJECT }}_Audit_Report_Metrics_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
    line: "Count of Transactional master rows,{{ tmr_21_result.stdout }}"
    create: yes
    insertafter: EOF
  delegate_to: localhost
  when: MR == "21"

##############################################

- name: Run MySQL query - Count Non-Transactional Master Rows
  shell: |
    mysql -h 172.16.10.49 -u SupportLead -P 6055 -pQw12s#fdga MobifinEliteTransactionEngine_QCell -e "SELECT COUNT(*) FROM TBLTransactionHistory WHERE TransactionType='NonTransactional'" | sed 's/\t/,/g' | awk 'NR==2 {print $1}'
  register: ntmr_18_result
  when: MR == "18"

#- name: Print output in file
#  lineinfile:
#    path: {{ DIRECTORY }}/{{ PROJECT }}_audit_report_db_{{ lookup('pipe', 'date +%d%m%Y') }}.txt
#    line: "Count of Non-Transactional master rows is {{ ntmr_18_result.stdout }}"
#  delegate_to: localhost
#  when: MR == "18"

- name: Print output in file
  lineinfile:
    path: "{{ DIRECTORY }}/{{ PROJECT }}_Audit_Report_Metrics_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
    line: "Count of Non-Transactional master rows,{{ ntmr_18_result.stdout }}"
    create: yes
    insertafter: EOF
  delegate_to: localhost
  when: MR == "18"

- name: Run MySQL query - Count Non-Transactional Master Rows
  shell: |
    mysql -h 172.16.10.49 -u SupportLead -P 6055 -pQw12s#fdga MobifinEliteTransactionEngine_QCell -e "SELECT COUNT(*) FROM TBLNonTransactionHST" | sed 's/\t/,/g' | awk 'NR==2 {print $1}'
  register: ntmr_20_21_result
  when: MR == "20" or MR == "21"

#- name: Print output in file
#  lineinfile:
#    path: {{ DIRECTORY }}/{{ PROJECT }}_audit_report_db_{{ lookup('pipe', 'date +%d%m%Y') }}.txt
#    line: "Count of Non-Transactional master rows is {{ ntmr_20_21_result.stdout }}"
#  delegate_to: localhost
#  when: MR == "20" or MR == "21"

- name: Print output in file
  lineinfile:
    path: "{{ DIRECTORY }}/{{ PROJECT }}_Audit_Report_Metrics_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
    line: "Count of Non-Transactional master rows,{{ ntmr_20_21_result.stdout }}"
    create: yes
    insertafter: EOF
  delegate_to: localhost
  when: MR == "20" or MR == "21"
