---
- name: Run MySQL query - Last 24 Hours API Requests
  shell: |
    mysql -h 172.16.10.49 -u SupportLead -P 6055 -pQw12s#fdga MobifinEliteTransactionEngine_QCell -e "SELECT ApiExternalId, COUNT(*) AS Count_Per_API_Name FROM TBLTransactionEventDetail WHERE CreateDate BETWEEN '2025-04-12 00:00:00' AND '2025-04-12 23:59:59'GROUP BY ApiExternalId" | sed 's/\t/,/g' > /tmp/last24H_API_Request_{{ lookup('pipe', 'date +%d%m%Y') }}.csv

- name: Copy csv file to Ansible server
  fetch:
    src: /tmp/last24H_API_Request_{{ lookup('pipe', 'date +%d%m%Y') }}.csv
    dest: "{{ DIRECTORY }}/{{ PROJECT }}_last24H_API_Request_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
    flat: yes

- name: Add blank row in CSV file
  lineinfile:
    path: "{{ DIRECTORY }}/{{ PROJECT }}_Audit_Report_Metrics_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
    line: ",,,"
    create: yes
    insertafter: EOF
  delegate_to: localhost
  run_once: true

- name: Append CSV data to destination file
  ansible.builtin.shell:
    cmd: |
      while IFS= read -r line; do
        echo "$line" >> {{ DIRECTORY }}/{{ PROJECT }}_Audit_Report_Metrics_{{ lookup('pipe', 'date +%d%m%Y') }}.csv
      done < "{{ DIRECTORY }}/{{ PROJECT }}_last24H_API_Request_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
  delegate_to: localhost

- name: Remove Last 24 Hours API Requests CSV
  file:
    path: /tmp/last24H_API_Request_{{ lookup('pipe', 'date +%d%m%Y') }}.csv
    state: absent

- name: Remove Last 24 Hours API Requests CSV
  file:
    path: "{{ DIRECTORY }}/{{ PROJECT }}_last24H_API_Request_{{ lookup('pipe', 'date +%d%m%Y') }}.csv"
    state: absent
  delegate_to: localhost
